version: 2
jobs:

  iosTest:
    macos:
      xcode: "9.0"
    working_directory: ~/TheBrain2.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-mobile-deps-{{ checksum "./mobileClient/package.json" }}
      - run:
          name: Install mobile packages
          working_directory: ~/TheBrain2.0/mobileClient
          command: npm install
      - save_cache:
          key: npm-mobile-deps-{{ checksum "./mobileClient/package.json" }}
          paths:
            - ~/TheBrain2.0/mobileClient/node_modules
      - run:
          name: Setup macosx kernel settings
          command: |
            sudo sysctl -w kern.maxfiles=5242880
            sudo sysctl -w kern.maxfilesperproc=524288
      - run:
          name: Boot up the simulator so its ready for testing
          command: 'xcrun simctl list | grep "Phone: iphone 7 (" -i | cut -d "(" -f 2 | cut -d ")" -f 1 | while read sim ; do xcrun simctl boot $sim ; done'
      - run:
          name: Installing Apple Simutils
          command: |
           curl "https://dl.dropboxusercontent.com/s/ycxj5wnaq8ocafz/applesimutils\?dl\=0" > /usr/local/bin/applesimutils
          chmod +x /usr/local/bin/applesimutils
      - run:
          name: Installing expo CLI
          command: npm install exp --global
      - run:
          name: Installing and link expo ios app
          command: |
            exp install:ios
            mkdir ~/TheBrain2.0/mobileClient/.expo/
            ln -s ~/.expo/ios-simulator-app-cache ~/TheBrain2.0/mobileClient/.expo/
      - run:
          name: Installing Detox globally
          command: npm install -g detox@7.0.0
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: E2E ios test
          working_directory: ~/TheBrain2.0/mobileClient
          command: |
            mv /tmp/workspace/package.json ~/TheBrain2.0/mobileClient/package.json
            DETOX_EXTERNAL_LINK=https://expo.io/@thebrain/thebrain-mobile-mobieIntroFix npm run e2e
      - run:
          name: Github Notification
          working_directory: ~/TheBrain2.0/mobileClient
          command: ONLY_NOTIFY_GITHUB=true WEB_ENDPOINT=`cat /tmp/workspace/webEndpoint` GRAPHQL_SERVER_URI=`cat /tmp/workspace/serviceEndpoint`/graphql ./node_modules/.bin/appr

workflows:
  version: 2
  test_release:
    jobs:
      - iosTest

